#!/bin/bash

echo "clear" >> .bashrc
echo -e "================================================="
echo -e "|                   AAPOO                       |"
echo -e "|    Terimaksih Kerana Telah Menggunakan AAPOO  |"
echo -e "|         Autoscript Ini Dibuat Oleh Hake       |"
echo -e "|           Sila Taip Command Dibawah           |"
echo -e "================================================="
echo -e ""
echo -e ""
echo -e ""
echo -e ""
echo -e ""
echo -e ""
echo -e "================================================="
echo -e ""  
echo -e "> menu         : Menampilkan daftar perintah"
echo -e "> new          : Membuat id user baru"
echo -e "> trial        : Membuat id trial"
echo -e "> delete       : Menghapus id user"
echo -e "> login        : Cek user login"
echo -e "> list         : Senarai id"
echo -e "> dropbear     : Limit login Dropbear"
echo -e "> ssh          : Limit login SSHD"
echo -e "> resvis       : Restart all service"
echo -e "> reboot       : Reboot VPS"
echo -e "> speedtest    : Speedtest VPS"
echo -e "> info         : Menampilkan informasi sistem"
echo -e "> about        : Info script auto install"
echo -e "> quit         : Keluar dari terminal SSH"
echo -e ""
echo -e "================================================="
