#!/bin/bash

echo -e "================================================="
echo -e ""  
echo -e "> menu         : Menampilkan daftar perintah"
echo -e "> new          : Membuat id user baru"
echo -e "> trial        : Membuat id trial"
echo -e "> delete       : Menghapus id user"
echo -e "> login        : Cek user login"
echo -e "> list         : Senarai id
echo -e "> dropbear     : Limit login Dropbear"
echo -e "> ssh          : Limit login SSHD"
echo -e "> resvis       : Restart service dropbear, webmin"
echo -e "                 squid3, OpenVPN dan SSH"
echo -e "> reboot       : Reboot VPS"
echo -e "> speedtest    : Speedtest VPS"
echo -e "> info         : Menampilkan informasi sistem"
echo -e "> about        : Info script auto install"
echo -e "> exit         : Keluar dari terminal SSH"
echo -e ""
echo -e "================================================="
